version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: milokhelo
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
